/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WebhooksRouteImport } from './routes/webhooks'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ReceiptsRouteImport } from './routes/receipts'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MerchantsRouteImport } from './routes/merchants'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HealthRouteImport } from './routes/health'
import { Route as FxRouteImport } from './routes/fx'
import { Route as EscrowRouteImport } from './routes/escrow'
import { Route as DeadLetterRouteImport } from './routes/dead-letter'
import { Route as ConfigRouteImport } from './routes/config'
import { Route as BalancesRouteImport } from './routes/balances'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersIndexRouteImport } from './routes/users/index'
import { Route as TransactionsIndexRouteImport } from './routes/transactions/index'
import { Route as UsersIdRouteImport } from './routes/users/$id'
import { Route as TransactionsIdRouteImport } from './routes/transactions/$id'

const WebhooksRoute = WebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptsRoute = ReceiptsRouteImport.update({
  id: '/receipts',
  path: '/receipts',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantsRoute = MerchantsRouteImport.update({
  id: '/merchants',
  path: '/merchants',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const FxRoute = FxRouteImport.update({
  id: '/fx',
  path: '/fx',
  getParentRoute: () => rootRouteImport,
} as any)
const EscrowRoute = EscrowRouteImport.update({
  id: '/escrow',
  path: '/escrow',
  getParentRoute: () => rootRouteImport,
} as any)
const DeadLetterRoute = DeadLetterRouteImport.update({
  id: '/dead-letter',
  path: '/dead-letter',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigRoute = ConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => rootRouteImport,
} as any)
const BalancesRoute = BalancesRouteImport.update({
  id: '/balances',
  path: '/balances',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsIndexRoute = TransactionsIndexRouteImport.update({
  id: '/transactions/',
  path: '/transactions/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIdRoute = UsersIdRouteImport.update({
  id: '/users/$id',
  path: '/users/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsIdRoute = TransactionsIdRouteImport.update({
  id: '/transactions/$id',
  path: '/transactions/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/balances': typeof BalancesRoute
  '/config': typeof ConfigRoute
  '/dead-letter': typeof DeadLetterRoute
  '/escrow': typeof EscrowRoute
  '/fx': typeof FxRoute
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/merchants': typeof MerchantsRoute
  '/notifications': typeof NotificationsRoute
  '/receipts': typeof ReceiptsRoute
  '/reports': typeof ReportsRoute
  '/review': typeof ReviewRoute
  '/webhooks': typeof WebhooksRoute
  '/transactions/$id': typeof TransactionsIdRoute
  '/users/$id': typeof UsersIdRoute
  '/transactions/': typeof TransactionsIndexRoute
  '/users/': typeof UsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/balances': typeof BalancesRoute
  '/config': typeof ConfigRoute
  '/dead-letter': typeof DeadLetterRoute
  '/escrow': typeof EscrowRoute
  '/fx': typeof FxRoute
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/merchants': typeof MerchantsRoute
  '/notifications': typeof NotificationsRoute
  '/receipts': typeof ReceiptsRoute
  '/reports': typeof ReportsRoute
  '/review': typeof ReviewRoute
  '/webhooks': typeof WebhooksRoute
  '/transactions/$id': typeof TransactionsIdRoute
  '/users/$id': typeof UsersIdRoute
  '/transactions': typeof TransactionsIndexRoute
  '/users': typeof UsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/balances': typeof BalancesRoute
  '/config': typeof ConfigRoute
  '/dead-letter': typeof DeadLetterRoute
  '/escrow': typeof EscrowRoute
  '/fx': typeof FxRoute
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/merchants': typeof MerchantsRoute
  '/notifications': typeof NotificationsRoute
  '/receipts': typeof ReceiptsRoute
  '/reports': typeof ReportsRoute
  '/review': typeof ReviewRoute
  '/webhooks': typeof WebhooksRoute
  '/transactions/$id': typeof TransactionsIdRoute
  '/users/$id': typeof UsersIdRoute
  '/transactions/': typeof TransactionsIndexRoute
  '/users/': typeof UsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/balances'
    | '/config'
    | '/dead-letter'
    | '/escrow'
    | '/fx'
    | '/health'
    | '/login'
    | '/merchants'
    | '/notifications'
    | '/receipts'
    | '/reports'
    | '/review'
    | '/webhooks'
    | '/transactions/$id'
    | '/users/$id'
    | '/transactions/'
    | '/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/balances'
    | '/config'
    | '/dead-letter'
    | '/escrow'
    | '/fx'
    | '/health'
    | '/login'
    | '/merchants'
    | '/notifications'
    | '/receipts'
    | '/reports'
    | '/review'
    | '/webhooks'
    | '/transactions/$id'
    | '/users/$id'
    | '/transactions'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/audit'
    | '/balances'
    | '/config'
    | '/dead-letter'
    | '/escrow'
    | '/fx'
    | '/health'
    | '/login'
    | '/merchants'
    | '/notifications'
    | '/receipts'
    | '/reports'
    | '/review'
    | '/webhooks'
    | '/transactions/$id'
    | '/users/$id'
    | '/transactions/'
    | '/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRoute
  BalancesRoute: typeof BalancesRoute
  ConfigRoute: typeof ConfigRoute
  DeadLetterRoute: typeof DeadLetterRoute
  EscrowRoute: typeof EscrowRoute
  FxRoute: typeof FxRoute
  HealthRoute: typeof HealthRoute
  LoginRoute: typeof LoginRoute
  MerchantsRoute: typeof MerchantsRoute
  NotificationsRoute: typeof NotificationsRoute
  ReceiptsRoute: typeof ReceiptsRoute
  ReportsRoute: typeof ReportsRoute
  ReviewRoute: typeof ReviewRoute
  WebhooksRoute: typeof WebhooksRoute
  TransactionsIdRoute: typeof TransactionsIdRoute
  UsersIdRoute: typeof UsersIdRoute
  TransactionsIndexRoute: typeof TransactionsIndexRoute
  UsersIndexRoute: typeof UsersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/webhooks': {
      id: '/webhooks'
      path: '/webhooks'
      fullPath: '/webhooks'
      preLoaderRoute: typeof WebhooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipts': {
      id: '/receipts'
      path: '/receipts'
      fullPath: '/receipts'
      preLoaderRoute: typeof ReceiptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchants': {
      id: '/merchants'
      path: '/merchants'
      fullPath: '/merchants'
      preLoaderRoute: typeof MerchantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fx': {
      id: '/fx'
      path: '/fx'
      fullPath: '/fx'
      preLoaderRoute: typeof FxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escrow': {
      id: '/escrow'
      path: '/escrow'
      fullPath: '/escrow'
      preLoaderRoute: typeof EscrowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dead-letter': {
      id: '/dead-letter'
      path: '/dead-letter'
      fullPath: '/dead-letter'
      preLoaderRoute: typeof DeadLetterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config': {
      id: '/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof ConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/balances': {
      id: '/balances'
      path: '/balances'
      fullPath: '/balances'
      preLoaderRoute: typeof BalancesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions/': {
      id: '/transactions/'
      path: '/transactions'
      fullPath: '/transactions/'
      preLoaderRoute: typeof TransactionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$id': {
      id: '/users/$id'
      path: '/users/$id'
      fullPath: '/users/$id'
      preLoaderRoute: typeof UsersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions/$id': {
      id: '/transactions/$id'
      path: '/transactions/$id'
      fullPath: '/transactions/$id'
      preLoaderRoute: typeof TransactionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRoute,
  BalancesRoute: BalancesRoute,
  ConfigRoute: ConfigRoute,
  DeadLetterRoute: DeadLetterRoute,
  EscrowRoute: EscrowRoute,
  FxRoute: FxRoute,
  HealthRoute: HealthRoute,
  LoginRoute: LoginRoute,
  MerchantsRoute: MerchantsRoute,
  NotificationsRoute: NotificationsRoute,
  ReceiptsRoute: ReceiptsRoute,
  ReportsRoute: ReportsRoute,
  ReviewRoute: ReviewRoute,
  WebhooksRoute: WebhooksRoute,
  TransactionsIdRoute: TransactionsIdRoute,
  UsersIdRoute: UsersIdRoute,
  TransactionsIndexRoute: TransactionsIndexRoute,
  UsersIndexRoute: UsersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
